project_id = "lzqvrnuzgfuyxbpyqfxh"

[functions.recommend-formateurs]
verify_jwt = true

[functions.generate-ministerial-document]
verify_jwt = true

[functions.generer-synthese-remontees]
verify_jwt = true

[functions.prevoir-recettes-tresor]
verify_jwt = true
