project_id = "lzqvrnuzgfuyxbpyqfxh"

[functions.recommend-formateurs]
verify_jwt = true

[functions.generate-ministerial-document]
verify_jwt = true

[functions.generer-synthese-remontees]
verify_jwt = true

[functions.prevoir-recettes-tresor]
verify_jwt = true

[functions.prevoir-recettes-par-type]
verify_jwt = true

[functions.generate-remontee-summary]
verify_jwt = true

[functions.generate-audio-summary]
verify_jwt = true

[functions.get-knowledge-base]
verify_jwt = false

[functions.chat-with-iasted]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-conversation-tags]
verify_jwt = true

